name: icue_face_sdk_example
description: Demonstrates how to use the icue_face_sdk plugin on Android.
publish_to: none

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  icue_face_sdk:
    path: ../
  shared_preferences: ^2.5.5

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/face_alice_1.png
    - assets/images/face_alice_2.png
    - assets/images/face_bob.png
