// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxW98Oxgw7OQl-HLvF8_5GRu2ndpEahKY',
    appId: '1:682367186948:web:6180308950468321b81d51',
    messagingSenderId: '682367186948',
    projectId: 'icueadmin',
    authDomain: 'icueadmin.firebaseapp.com',
    storageBucket: 'icueadmin.firebasestorage.app',
    measurementId: 'G-52QVSG2H04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxwHkHassOzRhz9haVrJhlHcmKygGkx0Q',
    appId: '1:682367186948:android:c3bdd27bd6139861b81d51',
    messagingSenderId: '682367186948',
    projectId: 'icueadmin',
    storageBucket: 'icueadmin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5N-IPU0OBIUiCDEYFfEkd9LgDO_zIPjc',
    appId: '1:682367186948:ios:5eac0ded1e1b29cab81d51',
    messagingSenderId: '682367186948',
    projectId: 'icueadmin',
    storageBucket: 'icueadmin.firebasestorage.app',
    iosBundleId: 'com.thoughtniques.icueadmin',
  );
}
