-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgFeTzKm2l7ockV1MJ
Ii2BEdGbDG7rPJRA5zFKhdzZJ1egCgYIKoZIzj0DAQehRANCAATSpxw7b+MqrXyX
kY/lBZfPYvknWMIPw+sPah9K3L6jH8Xo4XXQ4RTTLjM3CzCXnb52oU+LrzANW8OP
ZizlgrOf
-----END PRIVATE KEY-----